name: artifacts 

on: push

jobs:
  
  uploader:
    name: artifact-uploader
    runs-on: ubuntu-latest
    steps:
      - name: checkout file to os 
        uses: actions/checkout@v2
      - name: creates a file name songs.txt
        run: echo "beat it, what about us" > songs.txt
      - name:  uploads artifacts
        uses: actions/upload-artifact
  downloader:
    name: ubuntu-downloader
    runs-on: ubuntu-latest
    needs: [uploader]
    steps:
      - name: downloads artifact 
        uses: actions/download-artifact
      - name: print whats is the text file 
        run: cat songs.txt